config/routes.rb
LasAudio::Application.routes.draw do
  resources :musics

   root :to => 'musics#index'

end

app/models/music.rb
class Music < ActiveRecord::Base
  attr_accessible :name, :size, :file_type, :audio
  mount_uploader :audio, AudioUploader
  

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
    # GET /musics
    # GET /musics.json
    #require 'taglib'
    require "audioinfo"
    def index
        @musics = Music.all

        respond_to do |format|
            format.html # index.html.erb
            format.json { render json: @musics }
        end
    end

    # GET /musics/1
    # GET /musics/1.json
    def show
        @music = Music.find(params[:id])
        @tag_data_hash=tag_info("public#{@music.audio.to_s}")

        respond_to do |format|
            format.html # show.html.erb
            format.json { render json: @music }
        end
    end

    # GET /musics/new
    # GET /musics/new.json
    def new
        @music = Music.new

        respond_to do |format|
            format.html # new.html.erb
            format.json { render json: @music }
        end
    end

    # GET /musics/1/edit
    def edit
        #@music = Music.find(params[:id])
    end

    # POST /musics
    # POST /musics.json
    def create
        if !params["music"].nil?
            @music = Music.new(params[:music])
            @music.name=params["music"]["audio"].original_filename
            @music.size=params["music"]["audio"].size
            @music.content_type=params["music"]["audio"].content_type
        else
            raise "Please Choose file to upload"
        end
        respond_to do |format|
            if @music.save
                format.html { redirect_to @music, notice: 'Music was successfully created.' }
                format.json { render json: @music, status: :created, location: @music }
            else
                format.html { render action: "new" }
                format.json { render json: @music.errors, status: :unprocessable_entity }
            end
        end
    end

  # PUT /musics/1
  # PUT /musics/1.json
  def update
    #@music = Music.find(params[:id])
  end

    # DELETE /musics/1
    # DELETE /musics/1.json
    def destroy
        @music = Music.find(params[:id])
        @music.destroy
        respond_to do |format|
            format.html { redirect_to musics_url }
            format.json { head :no_content }
        end
    end
    ### function is used to show the tag details
    def tag_info(file_path)
        tag_hash={}
        AudioInfo.open(file_path) do |info|
            tag_hash[:artist]=info.artist
            tag_hash[:album]=info.album
            tag_hash[:title]=info.title
            tag_hash[:tracknum]=info.tracknum
            tag_hash[:bitrate]=info.bitrate
            tag_hash[:length]=info.length
            if info.info.class==Mp3Info
                tag_hash[:comments]=info.info.tag1.comments
                tag_hash[:samplerate]=info.info.samplerate
                tag_hash[:year]=info.info.tag2.TYER
            elsif info.info.class==MP4Info
                tag_hash[:genere]=info.info.GNRE
                tag_hash[:samplerate]=info.info.FREQUENCY
                tag_hash[:comment]=info.info.CMT
            end
        end
        return tag_hash
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LasAudio</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
	<%= yield %>
</div>

</body>
</html>

app/views/musics/_form.html.haml
#fileModal.modal.show.fade.in{:role=> "dialog"}
    = form_for @music do |f|
        .modal-header
            %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
            %h5 Upload File
        .modal-body
            - if @music.errors.any?
                #error_explanation.alert.alert-error
                    %h6= "#{pluralize(@music.errors.count, "error")} prohibited this music from being saved:"
                    %ul
                        -@music.errors.full_messages.each do |msg|
                            %li= msg
            .field
                = f.file_field :audio
        .modal-footer
            = f.submit 'Save',:class=>"btn btn-primary"
            = link_to 'Back', musics_path,:class=>"btn btn-primary"

app/views/musics/edit.html.haml
%h1 Editing music

= render 'form'

= link_to 'Show', @music
\|
= link_to 'Back', musics_path

app/views/musics/index.html.haml
%h4 Uploded Audio Files
.clearfix.pull-right.new_button
    = link_to new_music_path,{:class => 'btn btn-primary '} do
        %i.icon-upload.icon-white
        New Music
%table.table.table-bordered.table-striped
    %tr
        %th Name
        %th Size
        %th Type
        %th Uploaded Time
        %th Play
        %th Actions

    - @musics.each do |music|
        %tr
            %td= music.name
            %td= (music.size/1024).to_s.concat(' K.B.')
            %td= music.content_type
            %td= music.created_at
            %td
                %audio{controls: ""}
                    %source{src: music.audio, type:music.content_type }
                    %embed{height: "10", src:music.audio , width: "70"}
            %td
                = link_to '',music,{:class=>'icon-tags',:title=>"Show Tag",:method=>:get} 
                = link_to '', music, :class=>"icon-trash",:method => :delete, :delete=>"Delete",:data => { :confirm => 'Are you sure?' }

%br
  

app/views/musics/new.html.haml
%h2 New Music

= render 'form'

app/views/musics/show.html.haml
-str_header="Tag Details of #{@music.name}"
%h4 
	=str_header
-if notice.nil?
	-hide_class="hide"
-else
	-hide_class=""
%div{:class=>"alert alert-success #{hide_class}"}
	%p#notice=notice
%table.table.table-bordered.table-striped
	%tr
		%th Name
		%th Value
	-@tag_data_hash.each do |k,v|
		%tr
			%th=k.capitalize
			%td=v
   
=link_to 'Back', musics_path,:class=>"btn btn-primary"